name = "kossan-x"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true
account_id = "9a3ef399a2b9e3a9def76d0626695566"

[vars]
WORKER_URL = "https://kossan-x.liafis009.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "kossan-x-db"
database_id = "72745f1f-8611-490f-a4bf-ee695083cefe"

[triggers]
crons = ["*/5 * * * *"]
